import { ImageResponse } from 'next/og';
import { readFile } from 'node:fs/promises';
import { join } from 'node:path';

export const runtime = 'nodejs';
export const alt = 'Budget Planner — an instrument for your own money';
export const size = { width: 1200, height: 630 };
export const contentType = 'image/png';

/**
 * Social share image — "Instrument" palette, dark variant.
 *
 * Tokens matched to instrument.css (dark):
 *   canvas  #000000  (--canvas)
 *   panel   #0c0908  (--panel)
 *   ink     #f4f1f0  (--ink)
 *   ink-dim #bfb9b7  (--ink-dim)
 *   rule    #27211f  (--rule)
 *   orange  #ff5c1a  (--orange)
 *
 * Headline matches the home page <h1> verbatim so the card and the
 * landing reinforce each other. The screenshot is the same asset the
 * page ships, regenerated by scripts/capture-shots.mjs — the previous
 * card embedded a dashboard capture eight months out of date.
 *
 * Honesty: "Free to start", never "free forever" (PRODUCT.md rule 6).
 * No AI mention, no fabricated stats, no personal name or email.
 */
export default async function Image() {
	const shot = await readFile(
		join(process.cwd(), 'public', 'shots', 'dashboard-light.png'),
	);
	const shotSrc = `data:image/png;base64,${shot.toString('base64')}`;

	return new ImageResponse(
		(
			<div
				style={{
					width: '100%',
					height: '100%',
					display: 'flex',
					backgroundColor: '#000000',
					color: '#f4f1f0',
					fontFamily: 'sans-serif',
				}}
			>
				<div
					style={{
						display: 'flex',
						flexDirection: 'column',
						justifyContent: 'space-between',
						width: '58%',
						flexShrink: 0,
						padding: '58px 0 54px 62px',
					}}
				>
					<div style={{ fontSize: '26px', fontWeight: 700, letterSpacing: '-.02em' }}>
						Budget Planner
					</div>

					{/* Matches the home page h1 verbatim */}
					<div
						style={{
							fontSize: '64px',
							fontWeight: 800,
							lineHeight: 1.02,
							letterSpacing: '-.03em',
							display: 'flex',
							flexDirection: 'column',
							marginTop: '16px',
						}}
					>
						<span>An instrument for</span>
						<span>your own money.</span>
					</div>

					<div style={{ display: 'flex', flexDirection: 'column', gap: '20px' }}>
						{/* The accent, spent once */}
						<div
							style={{
								display: 'flex',
								width: '108px',
								height: '4px',
								backgroundColor: '#ff5c1a',
							}}
						/>
						<div
							style={{
								display: 'flex',
								fontSize: '20px',
								color: '#bfb9b7',
								gap: '24px',
							}}
						>
							<span>No bank linking</span>
							<span style={{ color: '#27211f' }}>&#183;</span>
							<span>Free to start</span>
							<span style={{ color: '#27211f' }}>&#183;</span>
							<span>budget.umbra.build</span>
						</div>
					</div>
				</div>

				{/* The real product, cropped flush to the edge */}
				<div
					style={{
						display: 'flex',
						width: '42%',
						alignItems: 'center',
						overflow: 'hidden',
						borderLeft: '1px solid #27211f',
						backgroundColor: '#0c0908',
					}}
				>
					<img
						alt=''
						src={shotSrc}
						width={880}
						height={550}
						style={{ objectFit: 'cover', objectPosition: 'left center' }}
					/>
				</div>
			</div>
		),
		{ ...size },
	);
}
