import { ImageResponse } from 'next/og';
import { readFile } from 'node:fs/promises';
import { join } from 'node:path';

export const runtime = 'nodejs';
export const alt = 'Budget Planner — your money has a number, you just haven’t seen it';
export const size = { width: 1200, height: 630 };
export const contentType = 'image/png';

/**
 * Social share image — "Plain Statement" palette.
 *
 * Tokens matched to statement.css (light):
 *   canvas  #fcfaf9  (--st-canvas)
 *   ink     #1a120f  (--st-ink)
 *   body    #4d4644  (--st-body)
 *   muted   #6e6765  (--st-muted)
 *   rule    #e0dbda  (--st-rule)
 *   signal  #c43518  (--st-signal)
 *
 * Headline matches the home page <h1> verbatim so the share card and the
 * landing reinforce each other.
 *
 * The screenshot is the same one the page ships, regenerated by
 * scripts/capture-shots.mjs — not a stale asset. The previous card
 * embedded a dashboard capture that was eight months out of date.
 *
 * Honesty: "Free to start", never "free forever" (PRODUCT.md rule 6).
 * No AI mention, no fabricated stats, no personal name or email.
 */
export default async function Image() {
	const shot = await readFile(
		join(process.cwd(), 'public', 'shots', 'dashboard-light.png'),
	);
	const shotSrc = `data:image/png;base64,${shot.toString('base64')}`;

	return new ImageResponse(
		(
			<div
				style={{
					width: '100%',
					height: '100%',
					display: 'flex',
					backgroundColor: '#fcfaf9',
					color: '#1a120f',
					fontFamily: 'sans-serif',
				}}
			>
				{/* Left column — wordmark, headline, meta */}
				<div
					style={{
						display: 'flex',
						flexDirection: 'column',
						justifyContent: 'space-between',
						width: '58%',
						flexShrink: 0,
						padding: '60px 0 56px 64px',
					}}
				>
					<div
						style={{
							fontSize: '27px',
							fontWeight: 700,
							letterSpacing: '-0.035em',
						}}
					>
						Budget Planner
					</div>

					{/* Headline — matches the home page h1 verbatim */}
					<div
						style={{
							fontSize: '66px',
							fontWeight: 700,
							lineHeight: 1.0,
							letterSpacing: '-0.035em',
							display: 'flex',
							flexDirection: 'column',
							marginTop: '18px',
						}}
					>
						<span>Your money has</span>
						<span>a number. You just</span>
						<span>haven&#8217;t seen it.</span>
					</div>

					<div style={{ display: 'flex', flexDirection: 'column', gap: '22px' }}>
						{/* One 2px signal rule — the system's accent, spent once */}
						<div
							style={{
								display: 'flex',
								width: '112px',
								height: '4px',
								backgroundColor: '#c43518',
							}}
						/>
						<div
							style={{
								display: 'flex',
								fontSize: '21px',
								color: '#4d4644',
								gap: '26px',
							}}
						>
							<span>No bank linking</span>
							<span style={{ color: '#e0dbda' }}>&#183;</span>
							<span>Free to start</span>
							<span style={{ color: '#e0dbda' }}>&#183;</span>
							<span>budget.umbra.build</span>
						</div>
					</div>
				</div>

				{/* Right column — the real product, cropped flush to the edge */}
				<div
					style={{
						display: 'flex',
						width: '42%',
						alignItems: 'center',
						overflow: 'hidden',
						borderLeft: '1px solid #e0dbda',
					}}
				>
					<img
						alt=''
						src={shotSrc}
						width={880}
						height={550}
						style={{ objectFit: 'cover', objectPosition: 'left center' }}
					/>
				</div>
			</div>
		),
		{ ...size },
	);
}
